### PR TITLE
kill command and specifiable authkeys arg

### PR DESCRIPTION
**Pull request by ChrisPritchard**
The specified keys allows running the server like `server --authorizedkeys c:\\users\\christopher\\.ssh\\id_rsa.pub 0.0.0.0:44444` which means you dont need to copy/create an adjacent authorised keys file. Just slightly easier, especially for debugging but also conceivably in regular scenarios.

The kill command wipes a connected client, which can be useful if the same client is connected multiple times for whatever reason and teh user wants to tidy things.

### CODE REVIEW

**Review by NHAS — CHANGES_REQUESTED** [review]
This looks good! Only change I'd like to make is that the client is explicitly instructed to kill itself. 
As you can ask clients to reconnect if server connection is lost. 

Currently, if a client is set to reconnect killing wont close the program.

**Comment by ChrisPritchard** [comment]
> 
> 
> This looks good! Only change I'd like to make is that the client is explicitly instructed to kill itself. As you can ask clients to reconnect if server connection is lost.
> 
> Currently, if a client is set to reconnect killing wont close the program.

Cool! I've switched to using a channel to send a kill command, rather than closing the connection.

**Comment by NHAS** [comment]
Why are you pausing in both the server and client?

Also on the server side, you should still kill the connection (in case is unresponsive)

**Comment by ChrisPritchard** [comment]
> 
> 
> Why are you pausing in both the server and client?
> 
> Also on the server side, you should still kill the connection (in case is unresponsive)

if i try to kill the connection on the server side it will error about trying to re-use a closed connection. i suppose i could catch and discard that error, taking it as proof of success?

the double pause is so the server waits until the client is dead before reporting success

**Pull request merged**
