### PR TITLE
Change timeouts on webserver to 5 seconds

### PR DESCRIPTION
**Pull request by TechSupportJosh**
The short timeouts often result in Windows clients (especially when using Invoke-WebRequest to fetch the client) erroring out as shown below:
image

Increasing the timeout to 5 seconds seems to fix the issue.

### CODE REVIEW

**Comment by NHAS** [comment]
Hi Josh, 

Thanks for this pull request! 
Im definitely going to merge this, however could I ask you to make the PR to the unstable branch? 

I'd also be interested in hearing about the network conditions (ping) between your rssh server and your windows box.

**Comment by TechSupportJosh** [comment]
In this case, there are two VMs running on my local machine, but they're bridged networking so they're going from my laptop -> router -> laptop, so it never leaves my local network. Unsure why this happens specifically with IWR

**Comment by NHAS** [comment]
Oh wild. I have roughly the same setup for testing and have never had this issue. 

I would say even 5 seconds is probably a little small just to cover our bases, feel free to change it to 20 seconds, then I'll merge :)

**Comment by TechSupportJosh** [comment]
Yeah it seems like a very random issue, but I've had other people reproduce the issue too (albeit, inconsistently)

**Comment by NHAS** [comment]
Awesome thanks

**Pull request merged**
